using Microsoft.AspNetCore.Mvc;
using RealEstateListingApi.Models;
using RealEstateListing.Services.Interfaces;
using RealEstateListingApi.Mapping;

namespace RealEstateListingApi.Controllers
{
    [ApiController]
    [Route("api/Listings")]
    public class ListingsController : ControllerBase
    {
        private readonly IUnitOfWork _unitOfWork;

        public ListingsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: api/Listings
        [HttpGet]
        [Tags("Listings Retrieval")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(IEnumerable<ListingDto>))]
        public async Task<ActionResult<IEnumerable<ListingDto>>> GetAllListings()
        {
            var listings = await _unitOfWork.Listings.GetAllAsync();
            var listingsDto = listings.Select(l => l.ToDto());
            return Ok(listingsDto);
        }

        // GET: api/Listings/{id}
        [HttpGet("{id}")]
        [Tags("Listings Retrieval")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ListingDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<ActionResult<ListingDto>> GetListingById(string id)
        {
            var listing = await _unitOfWork.Listings.GetByIdAsync(id);

            if (listing == null)
            {
                return NotFound($"Listing with ID {id} not found.");
            }

            return Ok(listing.ToDto());
        }

        // POST: api/Listings
        [HttpPost]
        [Tags("Listings Management")]
        [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(ListingDto))]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public async Task<ActionResult<ListingDto>> AddListing([FromBody] CreateListingDto createDto)
        {
            // ModelState validation is automatically handled by the [ApiController] attribute
            // for basic validation defined in the DTO.

            var newListing = createDto.ToEntity();
            
            // In a real app, you would typically generate a unique ID here if it's not auto-generated by the database.
            // For example: newListing.Id = Guid.NewGuid().ToString();

            await _unitOfWork.Listings.AddAsync(newListing);
            await _unitOfWork.CompleteAsync(); // This saves all changes

            // Map the newly created entity (which now has an ID) to a DTO for the response
            var createdListingDto = newListing.ToDto();

            return CreatedAtAction(nameof(GetListingById), new { id = createdListingDto.Id }, createdListingDto);
        }
    }
}

